### ISSUE TITLE
how to prevent the node server to launch if it is already running?

### ISSUE THREAD

**Issue by agamba** [ixmaps/IXmapsClient#74]
After removing the timeout script that was responsible of terminating the node server due to inactivity: (https://github.com/ixmaps/IXmapsClient/commit/b2b53c42000ac4397f5e8dfc59bd3788fde630ab), I've discovered  that closing the terminal window that initialized node sever, does not terminate the sever it self, or at least for a few minutes the addresses/port 127.0.0.1:2040 remains in use . It seems as if the node server keeps running it the background, and thus the only proper way to terminate it is to use control+c before closing the terminal window.

How to replicate this issue? (in Mac OS, but perhaps also in linux?)
1) Start the IXmapsClient (in a terminal)
2) Close the terminal window (without pressing control+c)
3) Start the IXmapsClient again
4) Then you get the following message ():

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:2040
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)

The EADDRINUSE indicates that 127.0.0.1:2040 is already in use. 

My suggestion is to include in the server.js script a ping or other test to determine whether the node server is already running at http://localhost:2040/. Or, adding a command that assures a complete termination of any previous node instance before attempting to initialize it again.

**Comment by Andrew-Clement** [comment]
I still get this error.  my preference is 
> adding a command that assures a complete termination of any previous node instance before attempting to initialize it again.

@vid Hi David, I wonder if you have some time to look at this lingering error? We've just re-launched IXmaps, which went viral over the last few days. The worldwide attention is great, but @agamba and @colinmccann have their hands full swatting at other issues that this public exposure has brought.
![pastedgraphic-23](https://cloud.githubusercontent.com/assets/12848029/24580445/3c677296-16d6-11e7-86f8-d6475c9a8958.png)

**Comment by vid** [comment]
I've added a solution to be tested in this PR https://github.com/ixmaps/IXmapsClient/pull/91
