### ISSUE TITLE
throw er; // Unhandled 'error' event   on launch

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/IXmapsClient#75]
Do you want to continue? (y/n): y
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:2040
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at GetAddrInfoReqWrap.asyncCallback [as callback](dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:82:10)
Macintosh-272:ixmaps-darwin andrewclementAir$

**Comment by agamba** [comment]
This issue is already reported in https://github.com/ixmaps/IXmapsClient/issues/74
