### ISSUE TITLE
/node_modules/cheerio/lib/parse.js:55 Cannot read property 'parent' of undefined

### ISSUE THREAD

**Issue by agamba** [ixmaps/IXmapsClient#76]
Anto:IXmapsClient-May26 antonio$ sudo npm start

> IXmapsClient@0.0.1 start /Users/antonio/mywebapps/IXmapsClient-May26
> node server.js

IXmapsClient server started at http://127.0.0.1:2040
Development mode: false
Connection
/Users/antonio/mywebapps/IXmapsClient-May26/node_modules/cheerio/lib/parse.js:55
    var oldParent = node.parent || node.root,
                        ^

TypeError: Cannot read property 'parent' of undefined
    at Function.exports.update (/Users/antonio/mywebapps/IXmapsClient-May26/node_modules/cheerio/lib/parse.js:55:25)
    at module.exports (/Users/antonio/mywebapps/IXmapsClient-May26/node_modules/cheerio/lib/parse.js:17:11)
    at Function.exports.load (/Users/antonio/mywebapps/IXmapsClient-May26/node_modules/cheerio/lib/static.js:19:14)
    at Request._callback (/Users/antonio/mywebapps/IXmapsClient-May26/lib/trset.js:18:21)
    at self.callback (/Users/antonio/mywebapps/IXmapsClient-May26/node_modules/request/request.js:200:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/Users/antonio/mywebapps/IXmapsClient-May26/node_modules/request/request.js:831:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)

npm ERR! Darwin 14.1.1
npm ERR! argv "/Users/antonio/Development/node-v4.2.6-darwin-x64/bin/node" "/Users/antonio/Development/node-v4.2.6-darwin-x64/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! IXmapsClient@0.0.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the IXmapsClient@0.0.1 start script 'node server.js'.
npm ERR! This is most likely a problem with the IXmapsClient package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls IXmapsClient
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/antonio/mywebapps/IXmapsClient-May26/npm-debug.log
Anto:IXmapsClient-May26 antonio$

**Comment by Andrew-Clement** [comment]
Hi Antonio,

Just got this message.  Should I ignore it and others like it?

A.


On 2016-05-26, at 7:57 AM, Antonio Gamba-Bari <notifications@github.com> wrote:

Anto:IXmapsClient-May26 antonio$ sudo npm start

IXmapsClient@0.0.1 start /Users/antonio/mywebapps/IXmapsClient-May26
node server.js

IXmapsClient server started at http://127.0.0.1:2040
Development mode: false
Connection
/Users/antonio/mywebapps/IXmapsClient-May26/node_modules/cheerio/lib/parse.js:55
var oldParent = node.parent || node.root,
^

TypeError: Cannot read property 'parent' of undefined
at Function.exports.update (/Users/antonio/mywebapps/IXmapsClient-May26/node_modules/cheerio/lib/parse.js:55:25)
at module.exports (/Users/antonio/mywebapps/IXmapsClient-May26/node_modules/cheerio/lib/parse.js:17:11)
at Function.exports.load (/Users/antonio/mywebapps/IXmapsClient-May26/node_modules/cheerio/lib/static.js:19:14)
at Request._callback (/Users/antonio/mywebapps/IXmapsClient-May26/lib/trset.js:18:21)
at self.callback (/Users/antonio/mywebapps/IXmapsClient-May26/node_modules/request/request.js:200:22)
at emitOne (events.js:77:13)
at Request.emit (events.js:169:7)
at Request.onRequestError (/Users/antonio/mywebapps/IXmapsClient-May26/node_modules/request/request.js:831:8)
at emitOne (events.js:77:13)
at ClientRequest.emit (events.js:169:7)

npm ERR! Darwin 14.1.1
npm ERR! argv "/Users/antonio/Development/node-v4.2.6-darwin-x64/bin/node" "/Users/antonio/Development/node-v4.2.6-darwin-x64/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! IXmapsClient@0.0.1 start: node server.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the IXmapsClient@0.0.1 start script 'node server.js'.
npm ERR! This is most likely a problem with the IXmapsClient package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node server.js
npm ERR! You can get their info via:
npm ERR! npm owner ls IXmapsClient
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /Users/antonio/mywebapps/IXmapsClient-May26/npm-debug.log
Anto:IXmapsClient-May26 antonio$

**Comment by colinmccann** [comment]
I assume / hope this is fixed with the client update to 1.1.1
