### ISSUE TITLE
Error: operation not permited (this.wrap = new raw.SocketWrap)

### ISSUE THREAD

**Issue by gabrieljcs** [ixmaps/IXmapsClient#90]
Running Fedora 25 (4.10.5-200.fc25.x86_64)

Just downloaded version 1.0.6 for Linux (IXmapsClient.1.0.6.linux.tar.gz), selected `00:all trsets`, as soon as the text `1 / 2469 Host hc-sc.gc.ca` appears the client crashes with the following error:

``
/home/[...]/IXmapsClient/node_modules/raw-socket/index.js:47
	this.wrap = new raw.SocketWrap (
	            ^

Error: Operation not permitted
    at Error (native)
    at new Socket (/home/[...]/IXmapsClient/node_modules/raw-socket/index.js:47:14)
    at Object.exports.createSocket (/home/[...]/IXmapsClient/node_modules/raw-socket/index.js:202:9)
    at trace (/home/[...]/IXmapsClient/lib/socket-trace.js:52:22)
    at module.exports (/home/[...]/IXmapsClient/lib/socket-trace.js:123:3)
    at wrapper (/home/[...]/IXmapsClient/node_modules/lodash/index.js:3592:19)
    at /home/[...]/IXmapsClient/node_modules/async/lib/async.js:718:13
    at iterate (/home/[...]/IXmapsClient/node_modules/async/lib/async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (/home/[...]/IXmapsClient/node_modules/async/lib/async.js:281:9)
    at _parallel (/home/[...]/IXmapsClient/node_modules/async/lib/async.js:717:9)
``

**Comment by colinmccann** [comment]
Thank you for reporting this issue. @agamba can you duplicate on your linux vm?

**Comment by Richard-Prins** [comment]
Identical issue on Windows 10 64-bit 1.0.6 with same selection as above (00: all trsets):
`C:\IXmapsClient\node_modules\raw-socket\index.js:47
        this.wrap = new raw.SocketWrap (
                    ^

Error: An attempt was made to access a socket in a way forbidden by its access permissions.

    at Error (native)
    at new Socket (C:\IXmapsClient\node_modules\raw-socket\index.js:47:14)
    at Object.exports.createSocket (C:\IXmapsClient\node_modules\raw-socket\index.js:202:9)
    at trace (C:\IXmapsClient\lib\socket-trace.js:52:22)
    at module.exports (C:\IXmapsClient\lib\socket-trace.js:123:3)
    at wrapper (C:\IXmapsClient\node_modules\lodash\index.js:3592:19)
    at C:\IXmapsClient\node_modules\async\lib\async.js:718:13
    at iterate (C:\IXmapsClient\node_modules\async\lib\async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (C:\IXmapsClient\node_modules\async\lib\async.js:281:9)
    at _parallel (C:\IXmapsClient\node_modules\async\lib\async.js:717:9)`

**Comment by Andrew-Clement** [comment]
Yes, thanks Richard for drawing this issue to our attention.

It works OK on my OSX 10.8.5
![pastedgraphic-6](https://cloud.githubusercontent.com/assets/12848029/24578941/fbd07e42-16b9-11e7-8720-2f20ccb2b6ba.png)

Perhaps I've missed something, but I was unable to determine which version IXmapsClient  I was running. I can see it was last modified in Dec 2016
![pastedgraphic-7](https://cloud.githubusercontent.com/assets/12848029/24578976/88ff6972-16ba-11e7-9948-36d61f8a5fe7.png)

For cases such as this, perhaps it would be good to include the version number in the preamble appearing in Terminal

![pastedgraphic-8](https://cloud.githubusercontent.com/assets/12848029/24578983/a815a682-16ba-11e7-9031-6cae03444e57.png)

**Comment by Richard-Prins** [comment]
For the Windows client the problem can be solved by running IXmapsClient.bat as an Administrator.
